name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Ensure we are in the correct directory where pom.xml is located
    - name: Change directory to Mega-CabService
      run: cd Mega-CabService

    # Run the Maven build with -X for debugging information
    - name: Build with Maven and run tests (with debug)
      run: mvn -B clean install -X -f Mega-CabService/pom.xml

    # Optional: Generate dependency graph using depgraph-maven-plugin
    - name: Generate dependency graph
      run: mvn -B com.github.ferstl:depgraph-maven-plugin:4.0.1:graph -DgraphFormat=json -f Mega-CabService/pom.xml
